# Arquivo de configurações para o script CTRL_SmartCap.py
data_smartCAP:
  feeder_path: 'C:/SmartRT/feeders/'
  utility: '391' #'63'
  feeder:
    - 'RMTQ1302'
  cenario:
    - '1,Caso_Base'
  controle:
#    - '0,Corrente'
#    - '1,Tensao'
#    - '2,kvar'
#    - '3,Tempo'
#    - '4,PF'
    - '5,Fixo'
    - '6,Desligado'
  month: 7 #[1, 7]
  type_day: 'DU' #['DU', 'DO']
  num_patamares: 24
  patamar_ini: 0
  patamar_fim: 24
  multiprocess: True
